### ISSUE TITLE
Do not store password in plaintext

### ISSUE THREAD

**Issue by obohrer** [sjp/GOMstreamer.NET#3]
This can be pretty harmful for users, especially if they use the same password for other services.

**Comment by sjp** [comment]
This is a good point. I was basically trying to mirror the behaviour of the OSX/Linux version when I was implementing this and figured that it was probably a reasonable time-saver.

However, due to the more "open" nature of file permissions on Windows, I can definitely see how this will not work as well.

When I get the time to work on this next I'll try to either remove the saving of user credentials, or at least make it an option.
